[build]
  command = "yarn build"
  publish = "dist"

  [[redirects]]
    from = "/.netlify/*"
    to = "/404"
    status = 404

  [[redirects]]
    from = "/en/reference/renderer-reference"
    to = "/en/reference/integrations-reference"



[dev]
  command = "yarn start"
  targetPort = 3001
  envFiles = [".env"]