[build]
  command = "yarn build"
  publish = "dist"

[[redirects]]
  from = "/analytics"
  to = "https://www.googletagmanager.com/gtag/js?id=G-BQJLEM0TPE"
  status = 200
  force = true
  headers = {X-From = "Netlify", access-control-allow-origin = "*"}
