[build]
  command = "pnpm build"
  publish = "dist"

[[redirects]]
  from = "/home"
  to = "/"
  status = 301

[[headers]]
  for = "/*"
  [headers.values]
      Access-Control-Allow-Origin = "https://glass.no"


[dev]
  command = "pnpm preview"
  targetPort = 5001
  envFiles = [".env"]
