name: 🚀 Deploy
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'

      - name: 🔨 Build Project
        run: |
          yarn install
          yarn build
          echo "::set-output name=dist-path::$(pwd)/dist"

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: appleboy/ssh-action@v0.1.7
        env:
          DIST_PATH: ${{ needs.build.outputs.dist-path }}
          APPLICATION_PATH: ${{ secrets.APPLICATION_PATH }}
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          envs: DIST_PATH,APPLICATION_PATH
          script_stop: true
          script: |
            pm2 stop 0
            cp -R $DIST_PATH $APPLICATION_PATH
            pm2 start "$APPLICATION_PATH/server/entry.mjs"
