name: 🚀 Deploy
on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'

      - name: 🔨 Build Project
        id: build-step
        run: |
          yarn install
          yarn build
          ls -la

      # - name: Deploy via SSH
      #   uses: appleboy/ssh-action@v0.1.7
      #   with:
      #     host: ${{ secrets.HOST }}
      #     username: ${{ secrets.USERNAME }}
      #     password: ${{ secrets.PASSWORD }}
      #     script_stop: true
      #     script: |
      #       pm2 stop 0
      #       cp -R "$(pwd)/dist/" ${{ secrets.APPLICATION_PATH }}
      #       pm2 start ${{ secrets.APPLICATION_PATH }}/server/entry.mjs
